eureka:
    instance:
        hostname: 172.20.30.11
        prefer-ip-address: false
        # needed to register services in JHipster Eureka by external host IP
        # not internal Docker cobntainer IP
        # this allows get and use services locally on developer machines
        #ip-address: 172.20.30.11
    client: 
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/

        
spring:
    datasource:
        url: jdbc:postgresql://172.20.30.11:5432/igvm?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
        username: test
        password: !QAZ2wsx                 
                
jhipster:
    security:
        authentication:
            jwt:
                secret: f3e616cc31a00e5c6f31c4df42b36ff1148eb3d4
    logging:
        logstash: # Forward logs to logstash only on Dev server
            enabled: true
            host: jhipster-logstash
    metrics:
        logs: # report metrics in the logs
            enabled: true
            report-frequency: 60 # in seconds                             


